/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006c4e",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-variant": "#333539",
        "background": "var(--background)",
        "on-surface": "var(--on-surface)",
        "surface-dim": "var(--background)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "var(--surface-container-low)",
        "error-container": "var(--error-container)",
        "inverse-surface": "var(--on-surface)",
        "outline": "#87948c",
        "surface-container-highest": "var(--surface-container-highest)",
        "tertiary": "var(--tertiary)",
        "on-primary": "var(--on-primary)",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error": "var(--on-error)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "outline-variant": "var(--outline-variant)",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#2f3035",
        "on-tertiary-fixed-variant": "#7e2a27",
        "on-surface-variant": "var(--on-surface-variant)",
        "tertiary-fixed-dim": "var(--tertiary)",
        "primary-container": "var(--primary-container)",
        "surface-tint": "var(--primary)",
        "secondary-container": "var(--secondary-container)",
        "surface-container": "var(--surface-container)",
        "primary-fixed-dim": "var(--primary)",
        "surface-bright": "#37393e",
        "on-secondary": "var(--on-secondary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "primary": "var(--primary)",
        "secondary": "var(--secondary)",
        "surface": "var(--surface)",
        "tertiary-fixed": "#ffdad6",
        "error": "var(--error)",
        "surface-container-high": "var(--surface-container-high)",
        "on-error-container": "var(--on-error-container)",
        "on-background": "var(--on-background)",
        "primary-fixed": "#86f8c9",
        "on-primary-fixed": "#002115",
        "secondary-fixed-dim": "var(--secondary)",
        "on-primary-fixed-variant": "#00513a",
        "on-tertiary": "var(--on-tertiary)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "gutter": "16px",
        "xl": "32px",
        "md": "16px",
        "margin": "24px",
        "sm": "8px",
        "xs": "4px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
