/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006c4e",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-container": "#560d0e",
        "tertiary-container": "#db726b",
        "surface-variant": "#333539",
        "background": "#111318",
        "on-surface": "#e2e2e8",
        "surface-dim": "#111318",
        "on-primary-container": "#003121",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "#1a1c20",
        "error-container": "#93000a",
        "inverse-surface": "#e2e2e8",
        "outline": "#87948c",
        "surface-container-highest": "#333539",
        "tertiary": "#ffb3ad",
        "on-primary": "#003827",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error": "#690005",
        "surface-container-lowest": "#0c0e12",
        "outline-variant": "#3d4943",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#2f3035",
        "on-tertiary-fixed-variant": "#7e2a27",
        "on-surface-variant": "#bccac1",
        "tertiary-fixed-dim": "#ffb3ad",
        "primary-container": "#26a37a",
        "surface-tint": "#68dbae",
        "secondary-container": "#3f465c",
        "surface-container": "#1e2024",
        "primary-fixed-dim": "#68dbae",
        "surface-bright": "#37393e",
        "on-secondary": "#283044",
        "on-secondary-container": "#adb4ce",
        "primary": "#68dbae",
        "secondary": "#bec6e0",
        "surface": "#111318",
        "tertiary-fixed": "#ffdad6",
        "error": "#ffb4ab",
        "surface-container-high": "#282a2e",
        "on-error-container": "#ffdad6",
        "on-background": "#e2e2e8",
        "primary-fixed": "#86f8c9",
        "on-primary-fixed": "#002115",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#00513a",
        "on-tertiary": "#5f1413"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "gutter": "16px",
        "xl": "32px",
        "md": "16px",
        "margin": "24px",
        "sm": "8px",
        "xs": "4px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
